> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5 Exciting ways to operate Numpy arrays


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- reshape
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='5 Exciting ways to operate Numpy arrays')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pratik2022000/5-exciting-ways-to-operate-numpy-arrays" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/pratik2022000/5-exciting-ways-to-operate-numpy-arrays


'https://jovian.ml/pratik2022000/5-exciting-ways-to-operate-numpy-arrays'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.reshape  
function2 = np.sort
function3 = ???
function4 = ???
function5 = ???

SyntaxError: invalid syntax (<ipython-input-5-cdc4db1efd08>, line 4)

# Function 1 - np.reshape(a, newshape, order='C')

Reshape Function helps to reshape our array into desired shape without changing its data

It takes 3 Parameters (2 Required and 1 optional)

### a = Numpy Array to be Reshaped

### newshape = New Shape ( Has to be compatible with current shape )

### Order(optional) = Can take one of the following {‘C’, ‘F’, ‘A’} 
where
C = C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest
F = ‘F’ means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest.
A =  ‘A’ means to read / write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.

### Returns - reshaped_array : ndarray

In [6]:
# Example 1 - working 
arr1 = [[1, 2, 3], 
        [5, 6, 7]]
np.reshape(arr1, (3,2))


array([[1, 2],
       [3, 5],
       [6, 7]])

In the above Example arr1 was of shape (2,3) we reshaped it as (3,2) without using order parameter

In [7]:
# Example 2 - working
arr2 = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]
np.reshape(arr2, (1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### To learn effect of order

In [8]:
# Example 2 - working using Order
arr2 = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]
np.reshape(arr2, (1,9), order ='F')

array([[1, 4, 7, 2, 5, 8, 3, 6, 9]])

In the above Example arr2 was of shape (3,3) we reshaped it as (1,9) with using 'F' Order

In [9]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = [[1, 2, 3],
        [4, 5, 6]]
np.reshape(arr3, (2,4))

ValueError: cannot reshape array of size 6 into shape (2,4)

In the above Example arr3 was of shape (2,3) we tried reshape it as (2, 4) , but it fails as the new shape isn't compatible with earlier one. To Fix such issues we have to use shape compatibble with current shape

This Function is extremely Useful when performing Operation on Numpy arrays and when we want to change their shapes for certain operatons 

In [10]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pratik2022000/5-exciting-ways-to-operate-numpy-arrays" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/pratik2022000/5-exciting-ways-to-operate-numpy-arrays


'https://jovian.ml/pratik2022000/5-exciting-ways-to-operate-numpy-arrays'

# Function 2 - np.sort(a, axis=-1, kind=None, order=None)

Sort Function helps to sort the array in desired Order

It takes 4 Parameters (1 Required and 3 optional)

### a = Numpy Array to be Reshaped

### axis(Optional) = Axis along which to sort. If None, the array is flattened before sorting. The default is -1, which sorts along the last axis.

### kind(optional) = {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}
where the types are Sorting algorithm. The default is ‘quicksort’. Note that both ‘stable’ and ‘mergesort’ use timsort or radix sort under the covers and, in general, the actual implementation will vary with data type. The ‘mergesort’ option is retained for backwards compatibility

### order(optional) = str or list of str

### Returns - sorted_array : ndarray


In [11]:
# Example 1 - working
arr4 = [[3, 9, 8],
        [1, 5, 9]]
np.sort(arr4)

array([[3, 8, 9],
       [1, 5, 9]])

In the above example arr4 is sorted in ascending order

In [17]:
# Example 2 - working
arr5 = [[10, 9, 8],
        [7, 6, 5],
        [4, 3, 2]]
np.sort(arr5, axis = 1)

array([[ 8,  9, 10],
       [ 5,  6,  7],
       [ 2,  3,  4]])

In the above example arr5 is sorted in ascending order along axis 1

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
arr6 = [[10, 9, 8],
        [7, 6, 5],
        [4, 3, 2]]
np.sort(arr6, axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

In the above example arr6 is fails to sort as the axis is out of bound. To fix this issue we have to maintain the axis within limits

sort() is extremely useful in sorting as it provides built in sorting algorithms such as mergesort, quicksort,etc. 

In [20]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pratik2022000/5-exciting-ways-to-operate-numpy-arrays" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/pratik2022000/5-exciting-ways-to-operate-numpy-arrays


'https://jovian.ml/pratik2022000/5-exciting-ways-to-operate-numpy-arrays'

## Function 3 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Function 3 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Function 4 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Function 5 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()